apiVersion: v1
kind: Pod
metadata:
  name: exu-news-database
  labels:
    app: exu-marabo-database
spec:
  containers:
    - name: exu-marabo-database-news-1
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: config-map-database