apiVersion: v1
kind: PersistentVolume
metadata:
  name: exu-marabo-database-pvolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/D/Projects/Dev/kubernets/volumes"