apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exu-marabo-database-pvclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

