apiVersion: v1
kind: Service
metadata:
  name: svc-exu-dasmatas-system
spec:
  type: NodePort
  selector: 
    app: exu-dasmatas-system
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
