apiVersion: apps/v1
kind: Deployment
metadata:
  name: exu-news-system
spec:
  replicas: 1
  template:
    metadata:
      name: exu-news-portal
      labels:
        app: exu-dasmatas-system
    spec:
      containers:
        - name: exu-dasmatas-system-news
          image: aluracursos/sistema-noticias:1
          envFrom:
            - configMapRef:
                name: "system-configmap"
          ports:
            - containerPort: 80
  selector:
    matchLabels: 
      app: exu-dasmatas-system