apiVersion: apps/v1
kind: Deployment
metadata:
  name: exu-dasmatas-system-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: exu-dasmatas-system
      labels:
        app: exu-dasmatas-system
    spec:
      containers:
        - name: exu-dasmatas-system-containers
          image: aluracursos/sistema-noticias:1
          envFrom:
            - configMapRef:
                name: system-configmap
          ports:
            - containerPort: 80
  selector:
    matchLabels: 
      app: exu-dasmatas-system