apiVersion: apps/v1
kind: Deployment
metadata:
  name: exu-dasmatas-system-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: exu-dasmatas-system
      labels:
        app: exu-dasmatas-system
    spec:
      containers:
        - name: exu-dasmatas-system-containers
          image: aluracursos/sistema-noticias:1
          envFrom:
            - configMapRef:
                name: system-configmap
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            failureThreshold: 15
            initialDelaySeconds: 3
  selector:
    matchLabels: 
      app: exu-dasmatas-system