apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-exu-caveira-deployment
spec:
  template:
    metadata:
      name: portal-exu-caveira
      labels:
        app: portal-exu-caveira
    spec:
      containers:
        - name: portal-exu-caveira-container
          image: aluracursos/portal-noticias:1
          envFrom:
            - configMapRef:
                name: portal-exu-caveira-config
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            failureThreshold: 15
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 10m
  replicas: 3
  selector:
    matchLabels: 
      app: portal-exu-caveira